### ISSUE TITLE
Support for PS 5.1?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [gngrninja/PSDsHook#2]
Would it be possible to downgrade .psd1 settings to include PowerShell 5.1? Using it as is has massive impact usage on Windows systems without PowerShell Core installed. Or is there some feature that requires PS 6?

**Comment by gngrninja** [comment]
There were some things in particular with sending files via the hook that 6.x made possible without a bit of ugly code. I can look into making certain features available for 5.1 users, such as sending embeds and messages.

**Comment by PrzemyslawKlys** [comment]
It would be nice. While I don't use Discord myself I was asked to add support for it in my module and thought I wouldn't reinvent the wheel. Also by adding this, you cover a larger part of the community.

**Comment by gngrninja** [comment]
@PrzemyslawKlys I've created version 0.1.5, which supports PowerShell version 5.1, sans sending binary files. Let me know what you think! It's in the gallery, and the release is here: https://github.com/gngrninja/PSDsHook/releases/tag/v0.1.5

**Comment by PrzemyslawKlys** [comment]
I was able to send test message but without using Classes.

```
Unable to find type [DiscordEmbed].
At C:\Program Files\WindowsPowerShell\Modules\PSBlackListChecker\Public\Start-ReportBlacklists.ps1:115 char:29
+             $embedBuilder = [DiscordEmbed]::New(
+                             ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (DiscordEmbed:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Unable to find type [DiscordColor].
At C:\Program Files\WindowsPowerShell\Modules\PSBlackListChecker\Public\Start-ReportBlacklists.ps1:120 char:17
+                 [DiscordColor]::New(
+                 ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (DiscordColor:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

You sure that gets loaded correctly in module?

**Comment by gngrninja** [comment]
You still need to use the using module call as in the examples at the top (even with it loaded).

Check out this example: https://github.com/gngrninja/PSDsHook/blob/master/examples/EmbedWithAllTheThings.ps1

**Comment by PrzemyslawKlys** [comment]
I saw this now. Sorry. Forgot that Classes require different loading. That's why I use C# Enums instead of built-in enums as well. Thanks

**Comment by gngrninja** [comment]
No problem! Hopefully that's re-worked in the future, as well as class ordering in the module file. We shall see in the future of PS.

**Comment by PrzemyslawKlys** [comment]
Weirdly enough VSCode complains module doesn't exists when using module

![image](https://user-images.githubusercontent.com/15063294/47955637-57288b80-df9b-11e8-9b94-0cd63c07a35f.png)

But it does work

**Comment by gngrninja** [comment]
Yeah it's not 100% there with classes yet. I get some random ones when I use some of my classes in other classes. It'll get there. Everything working for you now?

**Comment by PrzemyslawKlys** [comment]
Yep :-)

![image](https://user-images.githubusercontent.com/15063294/47955788-6b6d8800-df9d-11e8-80f8-d78ac2350261.png)

Just wondering if there's a need to use classes thou?

**Comment by gngrninja** [comment]
Yeah, classes make it was easier to build the embeds and keeps things modular. It's possible otherwise, but a lot messier. Classes are awesome, and I hope they get some more love in future releases.

For example, adding a field to the embed:
```powershell
    [void]AddField($field) 
    {
        if ($field.PsObject.TypeNames[0] -eq 'DiscordField')
        {
            Write-Verbose "Adding field to field array!"
            $this.Fields.Add($field) | Out-Null
        } 
        else
        {
            Write-Error "Did not receive a [DiscordField] object!"
        }
    }
```

Or with the color class having the ability to pass in hex colors, RGB, and some string representations as well. Then it returns the decimal color the Discord API expects (here's a portion of it for the RGB handling):

```powershell
    [string]ConvertFromRgb(
        [int]$r, 
        [int]$g, 
        [int]$b
    )
    {
        $hexR = [Convert]::ToString($r, 16).ToUpper()
        if ($hexR.Length -eq 1)
        {
            $hexR = "0$hexR"
        }

        $hexG = [Convert]::ToString($g, 16).ToUpper()
        if ($hexG.Length -eq 1)
        {
            $hexG = "0$hexG"
        }

        $hexB = [Convert]::ToString($b, 16).ToUpper()
        if ($hexB.Length -eq 1)
        {
            $hexB = "0$hexB"
        }

        [string]$hexValue     = "0x$hexR$hexG$hexB"
        $this.HexColor        = $HexValue
        [string]$decimalValue = $this.ConvertFromHex([int]$hexValue)

        return $decimalValue
    }

    [string]ToString()
    {
        return $this.DecimalColor
    }
```

**Comment by PrzemyslawKlys** [comment]
Would it? You could implement a function per each Class, add an Enum and it would be fairly modular as well :-) But I understand. Big issue is it's not going to be added to 5.1+ and PowerShell 6.0 has a long way to become widely used.

**Comment by PrzemyslawKlys** [comment]
```

function New-DiscordFooter {
    param(
        [string]$text = [string]::Empty
        [string]$icon_url = [string]::Empty
        [string]$proxy_icon_url = [string]::Empty
    )
    ....
}
```

That's how I do Teams messages.

**Comment by gngrninja** [comment]
What do ya mean not going to be added to 5.1+? Classes should be included in anything 5.1 and above, yes? Enums and functions work, but classes with constructors for different parameters as arguments is clean!

**Comment by PrzemyslawKlys** [comment]
I mean 5.1 is not getting any more love. If they add some ability to PS with further love it will not be backported. Unless you meant VSCode love.

**Comment by gngrninja** [comment]
Yeah, it works the way it is now, and good! Core is awesome and I tend to use that more than 5.1 (outside of work, of course). It's nice that it works on all platforms (including Pis now, albeit a bit slow...). The problem with core at the moment is that it is not already installed on all the machines like 5.x. 

I think it's gaining some traction though. The differences are there, and I see them with Pester and different output between the versions. Get-ChildItem even acts a bit differently between core and desktop. Going to close this issue out for now as it's working on 5.1!

Do open a new issue or feature request if you have any other ideas or something comes up, and thanks for the feedback!

**Comment by PrzemyslawKlys** [comment]
Thank you for quick fix :-)
