### ISSUE TITLE
Timestamp?

### ISSUE THREAD

**Issue by hauntedcpp** [gngrninja/PSDsHook#6]
Hello there, awesome repo

How would I add a timestamp, because every property of the embeds u showed are set to strings.

Greetings

**Comment by gngrninja** [comment]
The timestamp property on the embed? I will add that to the next release. 

Taking a look deeper later today/tonight, and should have something by the end of the weekend.

**Comment by gngrninja** [comment]
I updated the module, if you use:

```powershell
Update-Module PsDsHook -Force
```
it should pull in the changes.

The readme is also updated with the following:
Add a timestamp (no value, defaults to current time you use the command):

```powershell
$embedBuilder.AddTimeStamp()
```

Add a custom timestamp (pass in a value of type [DateTime] or one that can be resolved to [DateTime]):
```powershell
$embedBuilder.AddTimeStamp('5/3/24 05:50:21')
```

Let me know if you run into any issues.
